/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#12131a",
        "surface-dim": "#12131a",
        "surface-bright": "#383941",
        "surface-container-lowest": "#0d0e15",
        "surface-container-low": "#1a1b22",
        "surface-container": "#1e1f26",
        "surface-container-high": "#292931",
        "surface-container-highest": "#33343c",
        "surface-variant": "#33343c",
        "on-surface": "#e3e1ec",
        "on-surface-variant": "#bcc9cd",
        "inverse-surface": "#e3e1ec",
        "inverse-on-surface": "#2f3038",
        "outline": "#869397",
        "outline-variant": "#3d494c",
        "surface-tint": "#4cd7f6",
        "primary": "#4cd7f6",
        "on-primary": "#003640",
        "primary-container": "#06b6d4",
        "on-primary-container": "#00424f",
        "inverse-primary": "#00687a",
        "secondary": "#b4c5ff",
        "on-secondary": "#002a78",
        "secondary-container": "#0053db",
        "on-secondary-container": "#cdd7ff",
        "tertiary": "#ffb873",
        "on-tertiary": "#4b2800",
        "tertiary-container": "#e89337",
        "on-tertiary-container": "#5b3200",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#acedff",
        "primary-fixed-dim": "#4cd7f6",
        "on-primary-fixed": "#001f26",
        "on-primary-fixed-variant": "#004e5c",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary-fixed": "#ffdcbf",
        "tertiary-fixed-dim": "#ffb873",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6a3b00",
        "background": "#12131a",
        "on-background": "#e3e1ec",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "sidebar-width": "320px",
        "base": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "16px",
      },
      fontFamily: {
        "sans": ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "data-lg": ["'JetBrains Mono'", "monospace"],
        "data-md": ["'JetBrains Mono'", "monospace"],
        "data-sm": ["'JetBrains Mono'", "monospace"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
        "mono": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "display": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "data-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "data-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
